spring:
  datasource:
    url: jdbc:mysql://mysql.tracing-system.svc.cluster.local:3306/openshift?useSSL=false
    username: app
    password: app
  application:
    name: bank-service
  main:
    allow-bean-definition-overriding: true
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: update
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type: TRACE
        org.springframework.web: DEBUG
opentracing:
  jaeger:
    service-name: bank-service
    enable: true
    udp-sender:
      host: localhost
      port: 6831
  sampler:
    type: const
    param: 1
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /bank

baseUrl: http://localhost:9595/bank/accounts/getAccountDetailsByNumber/8119008115
subbaseUrl: http://localhost:8090/update-service/



#server:
#  error:
#    whitelabel:
#      enabled: false



#
#spring:
#  application:
#    name: app6

#tracing:
#  #url: http://jaeger-production-collector.tracing-system.svc.cluster.local:4318/v1/traces
#   url: http://localhost:4318/v1/traces
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#
#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

